In [1]:
import pandas as pd
import numpy as np

In [5]:
path = "/Users/qianj/Library/Mobile Documents/com~apple~CloudDocs/AA_2024-2026 job/Erdos_Project/MedicarePhysicianAndOtherPractitioners-byProvider"

In [13]:
def get_provider_types():
    df_provider_types = pd.DataFrame({'Rndrng_Prvdr_Type':[]})

    for year in range(2013,2024):
        df = pd.read_csv(f'{path}/PROV_{year}.csv')
        df = df.groupby('Rndrng_Prvdr_Type').size().rename(f'{year}_num').reset_index()
        df_provider_types = pd.merge(df_provider_types,df,how='outer')
    return df_provider_types

provider_types = get_provider_types()
provider_types

,Rndrng_Prvdr_Type,2013_num,2014_num,2015_num,2016_num,2017_num,2018_num,2019_num,2020_num,2021_num,2022_num,2023_num
0,Addiction Medicine,110.0,125.0,156.0,168.0,204.0,216.0,230.0,226.0,246.0,250.0,257.0
1,Adult Congenital Heart Disease,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,45.0,48.0,50.0
2,Advanced Heart Failure and Transplant Cardiology,NaN,NaN,NaN,NaN,25.0,479.0,563.0,649.0,713.0,752.0,791.0
3,All Other Suppliers,607.0,666.0,714.0,797.0,834.0,94.0,91.0,73.0,62.0,59.0,54.0
4,Allergy/ Immunology,NaN,NaN,NaN,3377.0,3392.0,3371.0,3385.0,3328.0,3296.0,3300.0,3270.0
...,...,...,...,...,...,...,...,...,...,...,...,...
127,Unknown Physician Specialty Code,82.0,113.0,286.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128,Unknown Supplier/Provider,52.0,27.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129,Unknown Supplier/Provider Specialty,NaN,NaN,NaN,12.0,7.0,7.0,11.0,12.0,13.0,19.0,23.0
130,Urology,8978.0,8981.0,8986.0,9015.0,9055.0,9098.0,9180.0,9142.0,9173.0,9217.0,9330.0
131,Vascular Surgery,2846.0,2915.0,3013.0,3135.0,3253.0,3369.0,3472.0,3526.0,3622.0,3712.0,3786.0

In [9]:
provider_types.to_csv(f'{path}/Number_Provider_by_type_10_years.csv')

In [14]:
df13 = pd.read_csv(f'{path}/PROV_2013.csv')
df14 = pd.read_csv(f'{path}/PROV_2014.csv')
df15 = pd.read_csv(f'{path}/PROV_2015.csv')
df16 = pd.read_csv(f'{path}/PROV_2016.csv')
df17 = pd.read_csv(f'{path}/PROV_2017.csv')
df18 = pd.read_csv(f'{path}/PROV_2018.csv')
df19 = pd.read_csv(f'{path}/PROV_2019.csv')
df20 = pd.read_csv(f'{path}/PROV_2020.csv')
df21 = pd.read_csv(f'{path}/PROV_2021.csv')
df22 = pd.read_csv(f'{path}/PROV_2022.csv')
df23 = pd.read_csv(f'{path}/PROV_2023.csv')

In [15]:
dfs = []
for year in range(2013,2024):
    temp = pd.read_csv(f'{path}/PROV_{year}.csv')
    temp['year'] = year
    dfs.append(temp)

df = pd.concat(dfs,ignore_index = True)
df

,Rndrng_NPI,Rndrng_Prvdr_Ent_Cd,Rndrng_Prvdr_State_Abrvtn,Rndrng_Prvdr_Type,Rndrng_Prvdr_Mdcr_Prtcptg_Ind,Tot_HCPCS_Cds,Tot_Benes,Tot_Srvcs,Tot_Sbmtd_Chrg,Tot_Mdcr_Alowd_Amt,...,Drug_Tot_HCPCS_Cds.1,Med_Tot_Benes,Med_Tot_Srvcs,Med_Sbmtd_Chrg,Med_Mdcr_Alowd_Amt,Med_Mdcr_Pymt_Amt,Med_Mdcr_Stdzd_Amt,Bene_Avg_Age,Bene_Avg_Risk_Scre,year
0,1003000126,I,MD,Internal Medicine,Y,22,665,1648.0,395335.00,146521.84,...,0.0,665.0,1648.0,395335.0,146521.84,116332.66,118271.40,74,2.1114,2013
1,1003000134,I,IL,Pathology,Y,13,3939,7517.0,1211425.00,282079.49,...,0.0,3939.0,7517.0,1211425.0,282079.49,217960.62,211192.64,76,1.0156,2013
2,1003000142,I,OH,Anesthesiology,Y,42,144,661.0,197224.00,63334.30,...,0.0,144.0,661.0,197224.0,63334.30,49752.77,49842.83,63,1.5662,2013
3,1003000407,I,PA,Family Practice,Y,37,436,1683.0,240818.00,174786.95,...,0.0,436.0,1683.0,240818.0,174786.95,138741.21,143708.38,76,1.8967,2013
4,1003000423,I,OH,Obstetrics/Gynecology,Y,33,63,320.0,31637.00,13176.47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56,1.1882,2013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12232189,1992999569,I,CA,Optometry,Y,6,16,24.0,3380.00,3010.25,...,0.0,16.0,24.0,3380.0,3010.25,1588.78,1269.53,72,0.8738,2023
12232190,1992999775,O,OR,Ambulatory Surgical Center,Y,24,228,317.0,2682450.00,1076800.05,...,0.0,228.0,317.0,2682450.0,1076800.05,856134.21,798167.83,74,0.9921,2023
12232191,1992999817,I,CA,Orthopedic Surgery,Y,13,18,44.0,21574.18,7201.29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71,0.7118,2023
12232192,1992999825,I,WA,Otolaryngology,Y,34,405,646.0,235765.00,91260.38,...,0.0,405.0,646.0,235765.0,91260.38,69628.19,61665.04,77,1.0682,2023
12232193,1992999874,I,VA,Internal Medicine,Y,8,286,582.0,197647.00,56028.21,...,0.0,286.0,582.0,197647.0,56028.21,44882.54,45412.71,77,2.6601,2023

# Deal with similar names

In [25]:
df['Rndrng_Prvdr_Type'] = df['Rndrng_Prvdr_Type'].astype(str).str.replace(" ", "", regex=False)

In [26]:
def new_provier_type():
    temp= df.groupby(['Rndrng_Prvdr_Type','year']).size().rename('num').reset_index()
    result = temp.pivot_table(
        index = 'Rndrng_Prvdr_Type',
        columns = 'year',
        values = 'num'
    )
    result.to_csv(f'{path}/Number_Provider_by_type_10_years.csv')
    return result
new_provier_type()

year,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
Rndrng_Prvdr_Type,,,,,,,,,,,
AddictionMedicine,110.0,125.0,156.0,168.0,204.0,216.0,230.0,226.0,246.0,250.0,257.0
AdultCongenitalHeartDisease,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,45.0,48.0,50.0
AdvancedHeartFailureandTransplantCardiology,NaN,NaN,NaN,NaN,25.0,479.0,563.0,649.0,713.0,752.0,791.0
AllOtherSuppliers,607.0,666.0,714.0,797.0,834.0,94.0,91.0,73.0,62.0,59.0,54.0
Allergy/Immunology,3296.0,3317.0,3358.0,3377.0,3392.0,3371.0,3385.0,3328.0,3296.0,3300.0,3270.0
...,...,...,...,...,...,...,...,...,...,...,...
UnknownPhysicianSpecialtyCode,82.0,113.0,286.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UnknownSupplier/Provider,52.0,27.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UnknownSupplier/ProviderSpecialty,NaN,NaN,NaN,12.0,7.0,7.0,11.0,12.0,13.0,19.0,23.0
Urology,8978.0,8981.0,8986.0,9015.0,9055.0,9098.0,9180.0,9142.0,9173.0,9217.0,9330.0
VascularSurgery,2846.0,2915.0,3013.0,3135.0,3253.0,3369.0,3472.0,3526.0,3622.0,3712.0,3786.0

In [ ]:
# change AmbulanceServiceSupplier to AmbulanceServiceProvider
df['Rndrng_Prvdr_Type'] = df['Rndrng_Prvdr_Type'].apply(lambda x: 'AmbulanceServiceProvider' if x=='AmbulanceServiceSupplier' else x)

In [30]:
new_provier_type()

year,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
Rndrng_Prvdr_Type,,,,,,,,,,,
AddictionMedicine,110.0,125.0,156.0,168.0,204.0,216.0,230.0,226.0,246.0,250.0,257.0
AdultCongenitalHeartDisease,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,45.0,48.0,50.0
AdvancedHeartFailureandTransplantCardiology,NaN,NaN,NaN,NaN,25.0,479.0,563.0,649.0,713.0,752.0,791.0
AllOtherSuppliers,607.0,666.0,714.0,797.0,834.0,94.0,91.0,73.0,62.0,59.0,54.0
Allergy/Immunology,3296.0,3317.0,3358.0,3377.0,3392.0,3371.0,3385.0,3328.0,3296.0,3300.0,3270.0
...,...,...,...,...,...,...,...,...,...,...,...
UnknownPhysicianSpecialtyCode,82.0,113.0,286.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UnknownSupplier/Provider,52.0,27.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UnknownSupplier/ProviderSpecialty,NaN,NaN,NaN,12.0,7.0,7.0,11.0,12.0,13.0,19.0,23.0
Urology,8978.0,8981.0,8986.0,9015.0,9055.0,9098.0,9180.0,9142.0,9173.0,9217.0,9330.0
VascularSurgery,2846.0,2915.0,3013.0,3135.0,3253.0,3369.0,3472.0,3526.0,3622.0,3712.0,3786.0

In [31]:
# change Hematology/Oncology to Hematology-Oncology
df['Rndrng_Prvdr_Type'] = df['Rndrng_Prvdr_Type'].apply(lambda x: 'Hematology-Oncology' if x=='Hematology/Oncology' else x)
new_provier_type()

year,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
Rndrng_Prvdr_Type,,,,,,,,,,,
AddictionMedicine,110.0,125.0,156.0,168.0,204.0,216.0,230.0,226.0,246.0,250.0,257.0
AdultCongenitalHeartDisease,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,45.0,48.0,50.0
AdvancedHeartFailureandTransplantCardiology,NaN,NaN,NaN,NaN,25.0,479.0,563.0,649.0,713.0,752.0,791.0
AllOtherSuppliers,607.0,666.0,714.0,797.0,834.0,94.0,91.0,73.0,62.0,59.0,54.0
Allergy/Immunology,3296.0,3317.0,3358.0,3377.0,3392.0,3371.0,3385.0,3328.0,3296.0,3300.0,3270.0
...,...,...,...,...,...,...,...,...,...,...,...
UnknownPhysicianSpecialtyCode,82.0,113.0,286.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UnknownSupplier/Provider,52.0,27.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UnknownSupplier/ProviderSpecialty,NaN,NaN,NaN,12.0,7.0,7.0,11.0,12.0,13.0,19.0,23.0
Urology,8978.0,8981.0,8986.0,9015.0,9055.0,9098.0,9180.0,9142.0,9173.0,9217.0,9330.0
VascularSurgery,2846.0,2915.0,3013.0,3135.0,3253.0,3369.0,3472.0,3526.0,3622.0,3712.0,3786.0

In [32]:
# change AnesthesiologistAssistants to AnesthesiologyAssistant
df['Rndrng_Prvdr_Type'] = df['Rndrng_Prvdr_Type'].apply(lambda x: 'AnesthesiologyAssistant' if x=='AnesthesiologistAssistants' else x)
new_provier_type()

year,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
Rndrng_Prvdr_Type,,,,,,,,,,,
AddictionMedicine,110.0,125.0,156.0,168.0,204.0,216.0,230.0,226.0,246.0,250.0,257.0
AdultCongenitalHeartDisease,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,45.0,48.0,50.0
AdvancedHeartFailureandTransplantCardiology,NaN,NaN,NaN,NaN,25.0,479.0,563.0,649.0,713.0,752.0,791.0
AllOtherSuppliers,607.0,666.0,714.0,797.0,834.0,94.0,91.0,73.0,62.0,59.0,54.0
Allergy/Immunology,3296.0,3317.0,3358.0,3377.0,3392.0,3371.0,3385.0,3328.0,3296.0,3300.0,3270.0
...,...,...,...,...,...,...,...,...,...,...,...
UnknownPhysicianSpecialtyCode,82.0,113.0,286.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UnknownSupplier/Provider,52.0,27.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UnknownSupplier/ProviderSpecialty,NaN,NaN,NaN,12.0,7.0,7.0,11.0,12.0,13.0,19.0,23.0
Urology,8978.0,8981.0,8986.0,9015.0,9055.0,9098.0,9180.0,9142.0,9173.0,9217.0,9330.0
VascularSurgery,2846.0,2915.0,3013.0,3135.0,3253.0,3369.0,3472.0,3526.0,3622.0,3712.0,3786.0

In [ ]:
# change CardiovascularDisease(Cardiology) to Cardiology
df['Rndrng_Prvdr_Type'] = df['Rndrng_Prvdr_Type'].apply(lambda x: 'Cardiology' if x=='CardiovascularDisease(Cardiology)' else x)
new_provier_type()

year,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
Rndrng_Prvdr_Type,,,,,,,,,,,
AddictionMedicine,110.0,125.0,156.0,168.0,204.0,216.0,230.0,226.0,246.0,250.0,257.0
AdultCongenitalHeartDisease,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,45.0,48.0,50.0
AdvancedHeartFailureandTransplantCardiology,NaN,NaN,NaN,NaN,25.0,479.0,563.0,649.0,713.0,752.0,791.0
AllOtherSuppliers,607.0,666.0,714.0,797.0,834.0,94.0,91.0,73.0,62.0,59.0,54.0
Allergy/Immunology,3296.0,3317.0,3358.0,3377.0,3392.0,3371.0,3385.0,3328.0,3296.0,3300.0,3270.0
...,...,...,...,...,...,...,...,...,...,...,...
UnknownPhysicianSpecialtyCode,82.0,113.0,286.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UnknownSupplier/Provider,52.0,27.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UnknownSupplier/ProviderSpecialty,NaN,NaN,NaN,12.0,7.0,7.0,11.0,12.0,13.0,19.0,23.0
Urology,8978.0,8981.0,8986.0,9015.0,9055.0,9098.0,9180.0,9142.0,9173.0,9217.0,9330.0
VascularSurgery,2846.0,2915.0,3013.0,3135.0,3253.0,3369.0,3472.0,3526.0,3622.0,3712.0,3786.0

In [34]:
# change CRNA to CertifiedRegisteredNurseAnesthetist(CRNA)
df['Rndrng_Prvdr_Type'] = df['Rndrng_Prvdr_Type'].apply(lambda x: 'CertifiedRegisteredNurseAnesthetist(CRNA)' if x=='CRNA' else x)
new_provier_type()

year,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
Rndrng_Prvdr_Type,,,,,,,,,,,
AddictionMedicine,110.0,125.0,156.0,168.0,204.0,216.0,230.0,226.0,246.0,250.0,257.0
AdultCongenitalHeartDisease,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,45.0,48.0,50.0
AdvancedHeartFailureandTransplantCardiology,NaN,NaN,NaN,NaN,25.0,479.0,563.0,649.0,713.0,752.0,791.0
AllOtherSuppliers,607.0,666.0,714.0,797.0,834.0,94.0,91.0,73.0,62.0,59.0,54.0
Allergy/Immunology,3296.0,3317.0,3358.0,3377.0,3392.0,3371.0,3385.0,3328.0,3296.0,3300.0,3270.0
...,...,...,...,...,...,...,...,...,...,...,...
UnknownPhysicianSpecialtyCode,82.0,113.0,286.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UnknownSupplier/Provider,52.0,27.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UnknownSupplier/ProviderSpecialty,NaN,NaN,NaN,12.0,7.0,7.0,11.0,12.0,13.0,19.0,23.0
Urology,8978.0,8981.0,8986.0,9015.0,9055.0,9098.0,9180.0,9142.0,9173.0,9217.0,9330.0
VascularSurgery,2846.0,2915.0,3013.0,3135.0,3253.0,3369.0,3472.0,3526.0,3622.0,3712.0,3786.0

In [36]:
# change CardiacElectrophysiology to ClinicalCardiacElectrophysiology
df['Rndrng_Prvdr_Type'] = df['Rndrng_Prvdr_Type'].apply(lambda x: 'ClinicalCardiacElectrophysiology' if x=='CardiacElectrophysiology' else x)
new_provier_type()

year,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
Rndrng_Prvdr_Type,,,,,,,,,,,
AddictionMedicine,110.0,125.0,156.0,168.0,204.0,216.0,230.0,226.0,246.0,250.0,257.0
AdultCongenitalHeartDisease,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,45.0,48.0,50.0
AdvancedHeartFailureandTransplantCardiology,NaN,NaN,NaN,NaN,25.0,479.0,563.0,649.0,713.0,752.0,791.0
AllOtherSuppliers,607.0,666.0,714.0,797.0,834.0,94.0,91.0,73.0,62.0,59.0,54.0
Allergy/Immunology,3296.0,3317.0,3358.0,3377.0,3392.0,3371.0,3385.0,3328.0,3296.0,3300.0,3270.0
...,...,...,...,...,...,...,...,...,...,...,...
UnknownPhysicianSpecialtyCode,82.0,113.0,286.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UnknownSupplier/Provider,52.0,27.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UnknownSupplier/ProviderSpecialty,NaN,NaN,NaN,12.0,7.0,7.0,11.0,12.0,13.0,19.0,23.0
Urology,8978.0,8981.0,8986.0,9015.0,9055.0,9098.0,9180.0,9142.0,9173.0,9217.0,9330.0
VascularSurgery,2846.0,2915.0,3013.0,3135.0,3253.0,3369.0,3472.0,3526.0,3622.0,3712.0,3786.0

In [37]:
# change ColorectalSurgery(formerlyproctology) to ColorectalSurgery(Proctology)
df['Rndrng_Prvdr_Type'] = df['Rndrng_Prvdr_Type'].apply(lambda x: 'ColorectalSurgery(Proctology)' if x=='ColorectalSurgery(formerlyproctology)' else x)
new_provier_type()

year,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
Rndrng_Prvdr_Type,,,,,,,,,,,
AddictionMedicine,110.0,125.0,156.0,168.0,204.0,216.0,230.0,226.0,246.0,250.0,257.0
AdultCongenitalHeartDisease,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,45.0,48.0,50.0
AdvancedHeartFailureandTransplantCardiology,NaN,NaN,NaN,NaN,25.0,479.0,563.0,649.0,713.0,752.0,791.0
AllOtherSuppliers,607.0,666.0,714.0,797.0,834.0,94.0,91.0,73.0,62.0,59.0,54.0
Allergy/Immunology,3296.0,3317.0,3358.0,3377.0,3392.0,3371.0,3385.0,3328.0,3296.0,3300.0,3270.0
...,...,...,...,...,...,...,...,...,...,...,...
UnknownPhysicianSpecialtyCode,82.0,113.0,286.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UnknownSupplier/Provider,52.0,27.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UnknownSupplier/ProviderSpecialty,NaN,NaN,NaN,12.0,7.0,7.0,11.0,12.0,13.0,19.0,23.0
Urology,8978.0,8981.0,8986.0,9015.0,9055.0,9098.0,9180.0,9142.0,9173.0,9217.0,9330.0
VascularSurgery,2846.0,2915.0,3013.0,3135.0,3253.0,3369.0,3472.0,3526.0,3622.0,3712.0,3786.0

In [38]:
# change Audiologist(billingindependently) to Audiologist
df['Rndrng_Prvdr_Type'] = df['Rndrng_Prvdr_Type'].apply(lambda x: 'Audiologist' if x=='Audiologist(billingindependently)' else x)
new_provier_type()

year,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
Rndrng_Prvdr_Type,,,,,,,,,,,
AddictionMedicine,110.0,125.0,156.0,168.0,204.0,216.0,230.0,226.0,246.0,250.0,257.0
AdultCongenitalHeartDisease,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,45.0,48.0,50.0
AdvancedHeartFailureandTransplantCardiology,NaN,NaN,NaN,NaN,25.0,479.0,563.0,649.0,713.0,752.0,791.0
AllOtherSuppliers,607.0,666.0,714.0,797.0,834.0,94.0,91.0,73.0,62.0,59.0,54.0
Allergy/Immunology,3296.0,3317.0,3358.0,3377.0,3392.0,3371.0,3385.0,3328.0,3296.0,3300.0,3270.0
...,...,...,...,...,...,...,...,...,...,...,...
UnknownPhysicianSpecialtyCode,82.0,113.0,286.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UnknownSupplier/Provider,52.0,27.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UnknownSupplier/ProviderSpecialty,NaN,NaN,NaN,12.0,7.0,7.0,11.0,12.0,13.0,19.0,23.0
Urology,8978.0,8981.0,8986.0,9015.0,9055.0,9098.0,9180.0,9142.0,9173.0,9217.0,9330.0
VascularSurgery,2846.0,2915.0,3013.0,3135.0,3253.0,3369.0,3472.0,3526.0,3622.0,3712.0,3786.0

In [39]:
# change Gynecological/Oncology to GynecologicalOncology
df['Rndrng_Prvdr_Type'] = df['Rndrng_Prvdr_Type'].apply(lambda x: 'GynecologicalOncology' if x=='Gynecological/Oncology' else x)
new_provier_type()

year,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
Rndrng_Prvdr_Type,,,,,,,,,,,
AddictionMedicine,110.0,125.0,156.0,168.0,204.0,216.0,230.0,226.0,246.0,250.0,257.0
AdultCongenitalHeartDisease,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,45.0,48.0,50.0
AdvancedHeartFailureandTransplantCardiology,NaN,NaN,NaN,NaN,25.0,479.0,563.0,649.0,713.0,752.0,791.0
AllOtherSuppliers,607.0,666.0,714.0,797.0,834.0,94.0,91.0,73.0,62.0,59.0,54.0
Allergy/Immunology,3296.0,3317.0,3358.0,3377.0,3392.0,3371.0,3385.0,3328.0,3296.0,3300.0,3270.0
...,...,...,...,...,...,...,...,...,...,...,...
UnknownPhysicianSpecialtyCode,82.0,113.0,286.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UnknownSupplier/Provider,52.0,27.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UnknownSupplier/ProviderSpecialty,NaN,NaN,NaN,12.0,7.0,7.0,11.0,12.0,13.0,19.0,23.0
Urology,8978.0,8981.0,8986.0,9015.0,9055.0,9098.0,9180.0,9142.0,9173.0,9217.0,9330.0
VascularSurgery,2846.0,2915.0,3013.0,3135.0,3253.0,3369.0,3472.0,3526.0,3622.0,3712.0,3786.0

In [40]:
# change IndependentDiagnosticTestingFacility to IndependentDiagnosticTestingFacility(IDTF)
df['Rndrng_Prvdr_Type'] = df['Rndrng_Prvdr_Type'].apply(lambda x: 'IndependentDiagnosticTestingFacility(IDTF)' if x=='IndependentDiagnosticTestingFacility' else x)
new_provier_type()

year,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
Rndrng_Prvdr_Type,,,,,,,,,,,
AddictionMedicine,110.0,125.0,156.0,168.0,204.0,216.0,230.0,226.0,246.0,250.0,257.0
AdultCongenitalHeartDisease,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,45.0,48.0,50.0
AdvancedHeartFailureandTransplantCardiology,NaN,NaN,NaN,NaN,25.0,479.0,563.0,649.0,713.0,752.0,791.0
AllOtherSuppliers,607.0,666.0,714.0,797.0,834.0,94.0,91.0,73.0,62.0,59.0,54.0
Allergy/Immunology,3296.0,3317.0,3358.0,3377.0,3392.0,3371.0,3385.0,3328.0,3296.0,3300.0,3270.0
...,...,...,...,...,...,...,...,...,...,...,...
UnknownPhysicianSpecialtyCode,82.0,113.0,286.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UnknownSupplier/Provider,52.0,27.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UnknownSupplier/ProviderSpecialty,NaN,NaN,NaN,12.0,7.0,7.0,11.0,12.0,13.0,19.0,23.0
Urology,8978.0,8981.0,8986.0,9015.0,9055.0,9098.0,9180.0,9142.0,9173.0,9217.0,9330.0
VascularSurgery,2846.0,2915.0,3013.0,3135.0,3253.0,3369.0,3472.0,3526.0,3622.0,3712.0,3786.0

In [41]:
# change IndependentDiagnosticTestingFacility to IndependentDiagnosticTestingFacility(IDTF)
df['Rndrng_Prvdr_Type'] = df['Rndrng_Prvdr_Type'].apply(lambda x: 'RegisteredDietitianorNutritionProfessional' if x=='RegisteredDietician/NutritionProfessional' else x)
df['Rndrng_Prvdr_Type'] = df['Rndrng_Prvdr_Type'].apply(lambda x: 'RadiationTherapyCenter' if x=='RadiationTherapy' else x)
df['Rndrng_Prvdr_Type'] = df['Rndrng_Prvdr_Type'].apply(lambda x: 'PublicHealthorWelfareAgency' if x=='PublicHealthWelfareAgency' else x)
df['Rndrng_Prvdr_Type'] = df['Rndrng_Prvdr_Type'].apply(lambda x: 'Psychologist,Clinical' if x=='Psychologist(billingindependently)' else x)
new_provier_type()

year,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
Rndrng_Prvdr_Type,,,,,,,,,,,
AddictionMedicine,110.0,125.0,156.0,168.0,204.0,216.0,230.0,226.0,246.0,250.0,257.0
AdultCongenitalHeartDisease,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,45.0,48.0,50.0
AdvancedHeartFailureandTransplantCardiology,NaN,NaN,NaN,NaN,25.0,479.0,563.0,649.0,713.0,752.0,791.0
AllOtherSuppliers,607.0,666.0,714.0,797.0,834.0,94.0,91.0,73.0,62.0,59.0,54.0
Allergy/Immunology,3296.0,3317.0,3358.0,3377.0,3392.0,3371.0,3385.0,3328.0,3296.0,3300.0,3270.0
...,...,...,...,...,...,...,...,...,...,...,...
UnknownPhysicianSpecialtyCode,82.0,113.0,286.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UnknownSupplier/Provider,52.0,27.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UnknownSupplier/ProviderSpecialty,NaN,NaN,NaN,12.0,7.0,7.0,11.0,12.0,13.0,19.0,23.0
Urology,8978.0,8981.0,8986.0,9015.0,9055.0,9098.0,9180.0,9142.0,9173.0,9217.0,9330.0
VascularSurgery,2846.0,2915.0,3013.0,3135.0,3253.0,3369.0,3472.0,3526.0,3622.0,3712.0,3786.0

In [42]:
df['Rndrng_Prvdr_Type'] = df['Rndrng_Prvdr_Type'].apply(lambda x: 'MammographyCenter' if x=='MammographicScreeningCenter' else x)
df['Rndrng_Prvdr_Type'] = df['Rndrng_Prvdr_Type'].apply(lambda x: 'MassImmunizerRosterBiller' if x=='MassImmunizationRosterBiller' else x)
df['Rndrng_Prvdr_Type'] = df['Rndrng_Prvdr_Type'].apply(lambda x: 'Obstetrics&Gynecology' if x=='Obstetrics/Gynecology' else x)
df['Rndrng_Prvdr_Type'] = df['Rndrng_Prvdr_Type'].apply(lambda x: 'OccupationalTherapistinPrivatePractice' if x=='Occupationaltherapist' else x)
new_provier_type()

year,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
Rndrng_Prvdr_Type,,,,,,,,,,,
AddictionMedicine,110.0,125.0,156.0,168.0,204.0,216.0,230.0,226.0,246.0,250.0,257.0
AdultCongenitalHeartDisease,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,45.0,48.0,50.0
AdvancedHeartFailureandTransplantCardiology,NaN,NaN,NaN,NaN,25.0,479.0,563.0,649.0,713.0,752.0,791.0
AllOtherSuppliers,607.0,666.0,714.0,797.0,834.0,94.0,91.0,73.0,62.0,59.0,54.0
Allergy/Immunology,3296.0,3317.0,3358.0,3377.0,3392.0,3371.0,3385.0,3328.0,3296.0,3300.0,3270.0
...,...,...,...,...,...,...,...,...,...,...,...
UnknownPhysicianSpecialtyCode,82.0,113.0,286.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UnknownSupplier/Provider,52.0,27.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UnknownSupplier/ProviderSpecialty,NaN,NaN,NaN,12.0,7.0,7.0,11.0,12.0,13.0,19.0,23.0
Urology,8978.0,8981.0,8986.0,9015.0,9055.0,9098.0,9180.0,9142.0,9173.0,9217.0,9330.0
VascularSurgery,2846.0,2915.0,3013.0,3135.0,3253.0,3369.0,3472.0,3526.0,3622.0,3712.0,3786.0

In [43]:
df['Rndrng_Prvdr_Type'] = df['Rndrng_Prvdr_Type'].apply(lambda x: 'OralSurgery(Dentistonly)' if x=='OralSurgery(Dentistsonly)' or x=='OralSurgery(dentistsonly)' else x)
new_provier_type()

year,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
Rndrng_Prvdr_Type,,,,,,,,,,,
AddictionMedicine,110.0,125.0,156.0,168.0,204.0,216.0,230.0,226.0,246.0,250.0,257.0
AdultCongenitalHeartDisease,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,45.0,48.0,50.0
AdvancedHeartFailureandTransplantCardiology,NaN,NaN,NaN,NaN,25.0,479.0,563.0,649.0,713.0,752.0,791.0
AllOtherSuppliers,607.0,666.0,714.0,797.0,834.0,94.0,91.0,73.0,62.0,59.0,54.0
Allergy/Immunology,3296.0,3317.0,3358.0,3377.0,3392.0,3371.0,3385.0,3328.0,3296.0,3300.0,3270.0
...,...,...,...,...,...,...,...,...,...,...,...
UnknownPhysicianSpecialtyCode,82.0,113.0,286.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UnknownSupplier/Provider,52.0,27.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UnknownSupplier/ProviderSpecialty,NaN,NaN,NaN,12.0,7.0,7.0,11.0,12.0,13.0,19.0,23.0
Urology,8978.0,8981.0,8986.0,9015.0,9055.0,9098.0,9180.0,9142.0,9173.0,9217.0,9330.0
VascularSurgery,2846.0,2915.0,3013.0,3135.0,3253.0,3369.0,3472.0,3526.0,3622.0,3712.0,3786.0

In [ ]:
df['Rndrng_Prvdr_Type'] = df['Rndrng_Prvdr_Type'].apply(lambda x: 'PhysicalTherapistinPrivatePractice' if x=='PhysicalTherapist' else x)
new_provier_type()

year,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
Rndrng_Prvdr_Type,,,,,,,,,,,
AddictionMedicine,110.0,125.0,156.0,168.0,204.0,216.0,230.0,226.0,246.0,250.0,257.0
AdultCongenitalHeartDisease,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,45.0,48.0,50.0
AdvancedHeartFailureandTransplantCardiology,NaN,NaN,NaN,NaN,25.0,479.0,563.0,649.0,713.0,752.0,791.0
AllOtherSuppliers,607.0,666.0,714.0,797.0,834.0,94.0,91.0,73.0,62.0,59.0,54.0
Allergy/Immunology,3296.0,3317.0,3358.0,3377.0,3392.0,3371.0,3385.0,3328.0,3296.0,3300.0,3270.0
...,...,...,...,...,...,...,...,...,...,...,...
UnknownPhysicianSpecialtyCode,82.0,113.0,286.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UnknownSupplier/Provider,52.0,27.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UnknownSupplier/ProviderSpecialty,NaN,NaN,NaN,12.0,7.0,7.0,11.0,12.0,13.0,19.0,23.0
Urology,8978.0,8981.0,8986.0,9015.0,9055.0,9098.0,9180.0,9142.0,9173.0,9217.0,9330.0
VascularSurgery,2846.0,2915.0,3013.0,3135.0,3253.0,3369.0,3472.0,3526.0,3622.0,3712.0,3786.0

In [46]:
df['Rndrng_Prvdr_Type'] = df['Rndrng_Prvdr_Type'].apply(lambda x: 'PortableX-RaySupplier' if x=='PortableX-ray' else x)
df['Rndrng_Prvdr_Type'] = df['Rndrng_Prvdr_Type'].apply(lambda x: 'UnknownSupplier/ProviderSpecialty' if x=='UnknownSupplier/Provider' else x)

new_provier_type()

year,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
Rndrng_Prvdr_Type,,,,,,,,,,,
AddictionMedicine,110.0,125.0,156.0,168.0,204.0,216.0,230.0,226.0,246.0,250.0,257.0
AdultCongenitalHeartDisease,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,45.0,48.0,50.0
AdvancedHeartFailureandTransplantCardiology,NaN,NaN,NaN,NaN,25.0,479.0,563.0,649.0,713.0,752.0,791.0
AllOtherSuppliers,607.0,666.0,714.0,797.0,834.0,94.0,91.0,73.0,62.0,59.0,54.0
Allergy/Immunology,3296.0,3317.0,3358.0,3377.0,3392.0,3371.0,3385.0,3328.0,3296.0,3300.0,3270.0
...,...,...,...,...,...,...,...,...,...,...,...
UnderseaandHyperbaricMedicine,NaN,NaN,NaN,NaN,NaN,1.0,82.0,111.0,120.0,127.0,126.0
UnknownPhysicianSpecialtyCode,82.0,113.0,286.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UnknownSupplier/ProviderSpecialty,52.0,27.0,15.0,12.0,7.0,7.0,11.0,12.0,13.0,19.0,23.0
Urology,8978.0,8981.0,8986.0,9015.0,9055.0,9098.0,9180.0,9142.0,9173.0,9217.0,9330.0
VascularSurgery,2846.0,2915.0,3013.0,3135.0,3253.0,3369.0,3472.0,3526.0,3622.0,3712.0,3786.0

In [47]:
df['Rndrng_Prvdr_Type'] = df['Rndrng_Prvdr_Type'].apply(lambda x: 'ClinicorGroupPractice' if x=='MultispecialtyClinic/GroupPractice' else x)

new_provier_type()

year,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
Rndrng_Prvdr_Type,,,,,,,,,,,
AddictionMedicine,110.0,125.0,156.0,168.0,204.0,216.0,230.0,226.0,246.0,250.0,257.0
AdultCongenitalHeartDisease,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,45.0,48.0,50.0
AdvancedHeartFailureandTransplantCardiology,NaN,NaN,NaN,NaN,25.0,479.0,563.0,649.0,713.0,752.0,791.0
AllOtherSuppliers,607.0,666.0,714.0,797.0,834.0,94.0,91.0,73.0,62.0,59.0,54.0
Allergy/Immunology,3296.0,3317.0,3358.0,3377.0,3392.0,3371.0,3385.0,3328.0,3296.0,3300.0,3270.0
...,...,...,...,...,...,...,...,...,...,...,...
UnderseaandHyperbaricMedicine,NaN,NaN,NaN,NaN,NaN,1.0,82.0,111.0,120.0,127.0,126.0
UnknownPhysicianSpecialtyCode,82.0,113.0,286.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UnknownSupplier/ProviderSpecialty,52.0,27.0,15.0,12.0,7.0,7.0,11.0,12.0,13.0,19.0,23.0
Urology,8978.0,8981.0,8986.0,9015.0,9055.0,9098.0,9180.0,9142.0,9173.0,9217.0,9330.0
VascularSurgery,2846.0,2915.0,3013.0,3135.0,3253.0,3369.0,3472.0,3526.0,3622.0,3712.0,3786.0

In [48]:
df['Rndrng_Prvdr_Type'] = df['Rndrng_Prvdr_Type'].apply(lambda x: 'Psychologist,Clinical' if x=='ClinicalPsychologist' else x)

new_provier_type()

year,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
Rndrng_Prvdr_Type,,,,,,,,,,,
AddictionMedicine,110.0,125.0,156.0,168.0,204.0,216.0,230.0,226.0,246.0,250.0,257.0
AdultCongenitalHeartDisease,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,45.0,48.0,50.0
AdvancedHeartFailureandTransplantCardiology,NaN,NaN,NaN,NaN,25.0,479.0,563.0,649.0,713.0,752.0,791.0
AllOtherSuppliers,607.0,666.0,714.0,797.0,834.0,94.0,91.0,73.0,62.0,59.0,54.0
Allergy/Immunology,3296.0,3317.0,3358.0,3377.0,3392.0,3371.0,3385.0,3328.0,3296.0,3300.0,3270.0
...,...,...,...,...,...,...,...,...,...,...,...
UnderseaandHyperbaricMedicine,NaN,NaN,NaN,NaN,NaN,1.0,82.0,111.0,120.0,127.0,126.0
UnknownPhysicianSpecialtyCode,82.0,113.0,286.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UnknownSupplier/ProviderSpecialty,52.0,27.0,15.0,12.0,7.0,7.0,11.0,12.0,13.0,19.0,23.0
Urology,8978.0,8981.0,8986.0,9015.0,9055.0,9098.0,9180.0,9142.0,9173.0,9217.0,9330.0
VascularSurgery,2846.0,2915.0,3013.0,3135.0,3253.0,3369.0,3472.0,3526.0,3622.0,3712.0,3786.0

In [50]:
df['Rndrng_Prvdr_Type'] = df['Rndrng_Prvdr_Type'].apply(lambda x: 'UndefinedPhysiciantype' if x=='UnknownPhysicianSpecialtyCode' else x)

new_provier_type()

year,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
Rndrng_Prvdr_Type,,,,,,,,,,,
AddictionMedicine,110.0,125.0,156.0,168.0,204.0,216.0,230.0,226.0,246.0,250.0,257.0
AdultCongenitalHeartDisease,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,45.0,48.0,50.0
AdvancedHeartFailureandTransplantCardiology,NaN,NaN,NaN,NaN,25.0,479.0,563.0,649.0,713.0,752.0,791.0
AllOtherSuppliers,607.0,666.0,714.0,797.0,834.0,94.0,91.0,73.0,62.0,59.0,54.0
Allergy/Immunology,3296.0,3317.0,3358.0,3377.0,3392.0,3371.0,3385.0,3328.0,3296.0,3300.0,3270.0
...,...,...,...,...,...,...,...,...,...,...,...
UndefinedPhysiciantype,82.0,113.0,286.0,287.0,454.0,390.0,328.0,207.0,209.0,208.0,218.0
UnderseaandHyperbaricMedicine,NaN,NaN,NaN,NaN,NaN,1.0,82.0,111.0,120.0,127.0,126.0
UnknownSupplier/ProviderSpecialty,52.0,27.0,15.0,12.0,7.0,7.0,11.0,12.0,13.0,19.0,23.0
Urology,8978.0,8981.0,8986.0,9015.0,9055.0,9098.0,9180.0,9142.0,9173.0,9217.0,9330.0
VascularSurgery,2846.0,2915.0,3013.0,3135.0,3253.0,3369.0,3472.0,3526.0,3622.0,3712.0,3786.0

# Mapping specialized the type into umbrella categories (with the help of chat)

In [51]:
mapping = {
    # ---------- Primary care ----------
    "FamilyPractice": "PrimaryCare",
    "InternalMedicine": "PrimaryCare",
    "GeneralPractice": "PrimaryCare",
    "PediatricMedicine": "PrimaryCare",
    "GeriatricMedicine": "PrimaryCare",

    # ---------- Cardiology / cardiovascular (non-surgical) ----------
    "Cardiology": "Cardiology",
    "InterventionalCardiology": "Cardiology",
    "ClinicalCardiacElectrophysiology": "Cardiology",
    "AdvancedHeartFailureandTransplantCardiology": "Cardiology",
    "AdultCongenitalHeartDisease": "Cardiology",
    "PeripheralVascularDisease": "Cardiology",
    "IntensiveCardiacRehabilitation": "Cardiology",

    # ---------- Cardiothoracic / vascular surgery ----------
    "CardiacSurgery": "CardioVascularSurgery",
    "ThoracicSurgery": "CardioVascularSurgery",
    "VascularSurgery": "CardioVascularSurgery",

    # ---------- Oncology / hematology ----------
    "Hematology": "OncologyHeme",
    "Hematology-Oncology": "OncologyHeme",
    "MedicalOncology": "OncologyHeme",
    "GynecologicalOncology": "OncologyHeme",
    "SurgicalOncology": "OncologyHeme",
    "RadiationOncology": "OncologyHeme",
    "HematopoieticCellTransplantationandCellularTherapy": "OncologyHeme",

    # ---------- Surgery (other) ----------
    "GeneralSurgery": "SurgeryOther",
    "ColorectalSurgery(Proctology)": "SurgeryOther",
    "HandSurgery": "SurgeryOther",
    "Neurosurgery": "SurgeryOther",
    "OrthopedicSurgery": "SurgeryOther",
    "PlasticandReconstructiveSurgery": "SurgeryOther",
    "Urology": "SurgeryOther",
    "Otolaryngology": "SurgeryOther",
    "MaxillofacialSurgery": "SurgeryOther",
    "OralSurgery(Dentistonly)": "SurgeryOther",
    "Podiatry": "SurgeryOther",
    "MicrographicDermatologicSurgery": "SurgeryOther",

    # ---------- OB/GYN ----------
    "Obstetrics&Gynecology": "OBGYN",
    "CertifiedNurseMidwife": "OBGYN",

    # ---------- Anesthesia ----------
    "Anesthesiology": "Anesthesia",
    "CertifiedRegisteredNurseAnesthetist(CRNA)": "Anesthesia",
    "AnesthesiologyAssistant": "Anesthesia",
    "DentalAnesthesiology": "Anesthesia",

    # ---------- Acute care / hospital ----------
    "EmergencyMedicine": "AcuteCare",
    "CriticalCare(Intensivists)": "AcuteCare",
    "Hospitalist": "AcuteCare",

    # ---------- Behavioral health / addiction ----------
    "Psychiatry": "BehavioralHealth",
    "GeriatricPsychiatry": "BehavioralHealth",
    "Neuropsychiatry": "BehavioralHealth",
    "Psychologist,Clinical": "BehavioralHealth",
    "LicensedClinicalSocialWorker": "BehavioralHealth",
    "AddictionMedicine": "BehavioralHealth",
    "OpioidTreatmentProgram": "BehavioralHealth",

    # ---------- Radiology / imaging ----------
    "DiagnosticRadiology": "RadiologyImaging",
    "InterventionalRadiology": "RadiologyImaging",
    "NuclearMedicine": "RadiologyImaging",
    "MammographyCenter": "RadiologyImaging",
    "PortableX-RaySupplier": "RadiologyImaging",

    # ---------- Lab / pathology ----------
    "ClinicalLaboratory": "LabPathology",
    "Pathology": "LabPathology",
    "SlidePreparationFacility": "LabPathology",

    # ---------- Rehab / therapy / conservative MSK ----------
    "PhysicalMedicineandRehabilitation": "RehabTherapy",
    "PhysicalTherapistinPrivatePractice": "RehabTherapy",
    "OccupationalTherapistinPrivatePractice": "RehabTherapy",
    "SpeechLanguagePathologist": "RehabTherapy",
    "Chiropractic": "RehabTherapy",
    "OsteopathicManipulativeMedicine": "RehabTherapy",
    "SportsMedicine": "RehabTherapy",

    # ---------- Vision / hearing ----------
    "Ophthalmology": "VisionHearing",
    "Optometry": "VisionHearing",
    "Audiologist": "VisionHearing",

    # ---------- Other medical specialties ----------
    "Allergy/Immunology": "MedicalSpecialtyOther",
    "Endocrinology": "MedicalSpecialtyOther",
    "Gastroenterology": "MedicalSpecialtyOther",
    "InfectiousDisease": "MedicalSpecialtyOther",
    "Nephrology": "MedicalSpecialtyOther",
    "Neurology": "MedicalSpecialtyOther",
    "PulmonaryDisease": "MedicalSpecialtyOther",
    "Rheumatology": "MedicalSpecialtyOther",
    "SleepMedicine": "MedicalSpecialtyOther",
    "PreventiveMedicine": "MedicalSpecialtyOther",
    "MedicalGeneticsandGenomics": "MedicalSpecialtyOther",
    "MedicalToxicology": "MedicalSpecialtyOther",
    "UnderseaandHyperbaricMedicine": "MedicalSpecialtyOther",
    "PainManagement": "MedicalSpecialtyOther",
    "InterventionalPainManagement": "MedicalSpecialtyOther",
    "Dermatology": "MedicalSpecialtyOther",
    "Dentist": "MedicalSpecialtyOther",
    "Dentistonly": "MedicalSpecialtyOther",  # (in case of weird variants)
    "DentalAnesthesiology": "Anesthesia",     # already above, kept here for clarity

    # ---------- Advanced practice providers ----------
    "NursePractitioner": "APP",
    "PhysicianAssistant": "APP",
    "CertifiedClinicalNurseSpecialist": "APP",
    "CertifiedNurseMidwife": "OBGYN",  # already above

    # ---------- Pharmacy / nutrition ----------
    "Pharmacy": "PharmacyNutrition",
    "RegisteredDietitianorNutritionProfessional": "PharmacyNutrition",

    # ---------- Facilities / suppliers / programs ----------
    "ClinicorGroupPractice": "FacilitySupplierProgram",
    "AmbulatorySurgicalCenter": "FacilitySupplierProgram",
    "AmbulanceServiceProvider": "FacilitySupplierProgram",
    "IndependentDiagnosticTestingFacility(IDTF)": "FacilitySupplierProgram",
    "HomeInfusionTherapyServices": "FacilitySupplierProgram",
    "HospiceandPalliativeCare": "FacilitySupplierProgram",
    "PublicHealthorWelfareAgency": "FacilitySupplierProgram",
    "MassImmunizerRosterBiller": "FacilitySupplierProgram",
    "CentralizedFlu": "FacilitySupplierProgram",
    "MedicareDiabetesPreventiveProgram": "FacilitySupplierProgram",
    "AllOtherSuppliers": "FacilitySupplierProgram",

    # ---------- Unknown / undefined ----------
    "UndefinedPhysiciantype": "UnknownOther",
    "UnknownSupplier/ProviderSpecialty": "UnknownOther",
}

In [52]:
df['Rndrng_Prvdr_Type'] = df['Rndrng_Prvdr_Type'].map(mapping).fillna('MedicalSpecialtyOther')
new_provier_type()

year,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
Rndrng_Prvdr_Type,,,,,,,,,,,
APP,116830.0,130512.0,147360.0,166234.0,185849.0,204861.0,225354.0,237409.0,256189.0,278002.0,296492.0
AcuteCare,41635.0,42978.0,44244.0,45597.0,51887.0,59398.0,62922.0,65860.0,68170.0,70531.0,72875.0
Anesthesia,75730.0,77532.0,79691.0,81715.0,83932.0,85953.0,87865.0,88775.0,90379.0,92363.0,94878.0
BehavioralHealth,52962.0,54410.0,55925.0,57720.0,58851.0,60104.0,60515.0,56242.0,53963.0,52189.0,51090.0
CardioVascularSurgery,6453.0,6517.0,6599.0,6732.0,6895.0,6999.0,7098.0,7105.0,7236.0,7333.0,7449.0
Cardiology,24192.0,24464.0,24635.0,25077.0,25530.0,25957.0,26349.0,26643.0,26881.0,27160.0,27470.0
FacilitySupplierProgram,55301.0,58792.0,60215.0,60416.0,59806.0,58056.0,56975.0,56540.0,58756.0,58420.0,57136.0
LabPathology,14283.0,14454.0,14526.0,14613.0,14710.0,14805.0,14774.0,14933.0,15304.0,15523.0,15293.0
MedicalSpecialtyOther,74991.0,76728.0,78479.0,80363.0,82250.0,83724.0,85388.0,86223.0,87319.0,88533.0,89876.0
OBGYN,28478.0,28410.0,28185.0,28128.0,27845.0,27638.0,27375.0,25783.0,25800.0,24881.0,24209.0
OncologyHeme,17143.0,17500.0,17916.0,18323.0,18827.0,19219.0,19561.0,19866.0,20211.0,20533.0,20886.0
PharmacyNutrition,1720.0,1748.0,1952.0,2006.0,2096.0,3001.0,3415.0,3743.0,5373.0,5464.0,5296.0
PrimaryCare,187117.0,189646.0,192101.0,194428.0,191351.0,186547.0,185870.0,182671.0,183237.0,182609.0,182731.0
RadiologyImaging,31427.0,31520.0,31743.0,32287.0,32757.0,33254.0,33739.0,34014.0,34378.0,34893.0,35546.0
RehabTherapy,89196.0,91379.0,94788.0,98037.0,102190.0,106821.0,112129.0,111157.0,119527.0,125310.0,130846.0
SurgeryOther,87458.0,87946.0,88199.0,88746.0,89341.0,89867.0,90373.0,89616.0,90038.0,90248.0,90477.0
UnknownOther,134.0,140.0,301.0,299.0,461.0,397.0,339.0,219.0,222.0,227.0,241.0
VisionHearing,51201.0,51981.0,52518.0,53237.0,54109.0,54861.0,55829.0,54743.0,55771.0,56074.0,56552.0

In [57]:
def save_each_year(path,file_name):
    col = df.columns.tolist()
    col = [c for c in col if c!='year']
    for year in range(2013,2024):
        temp = df[df['year']==year][col]
        temp.to_csv(f'{path}/{file_name}_{year}.csv')
    return

In [58]:
file_name = 'PROV_TYPE'

save_each_year(path,file_name)

# Deal with non-integer num of service

In [ ]:
mask_not_int = (df['Tot_Srvcs']%1!=0)
df[mask_not_int]

,Rndrng_NPI,Rndrng_Prvdr_Ent_Cd,Rndrng_Prvdr_State_Abrvtn,Rndrng_Prvdr_Type,Rndrng_Prvdr_Mdcr_Prtcptg_Ind,Tot_HCPCS_Cds,Tot_Benes,Tot_Srvcs,Tot_Sbmtd_Chrg,Tot_Mdcr_Alowd_Amt,...,Drug_Tot_HCPCS_Cds.1,Med_Tot_Benes,Med_Tot_Srvcs,Med_Sbmtd_Chrg,Med_Mdcr_Alowd_Amt,Med_Mdcr_Pymt_Amt,Med_Mdcr_Stdzd_Amt,Bene_Avg_Age,Bene_Avg_Risk_Scre,year
80,1003006180,O,NV,FacilitySupplierProgram,Y,8,8167,94896.8,14337276.69,6203937.48,...,0.0,8167.0,94896.8,14337276.69,6203937.48,4817379.63,5338018.57,68,2.1790,2013
255,1003013780,O,NJ,FacilitySupplierProgram,Y,3,237,59679.9,3352574.90,2065571.15,...,0.0,237.0,59679.9,3352574.90,2065571.15,1643939.93,1854626.11,75,5.4128,2013
285,1003015355,O,IL,FacilitySupplierProgram,Y,3,36,918.3,29283.00,24088.70,...,0.0,36.0,918.3,29283.00,24088.70,19092.80,16475.20,75,1.6004,2013
373,1003019704,O,WI,FacilitySupplierProgram,Y,2,51,981.6,49418.63,31727.59,...,0.0,51.0,981.6,49418.63,31727.59,25102.34,26726.38,79,1.7709,2013
420,1003023276,I,VA,SurgeryOther,Y,110,334,1932.5,417846.00,119747.32,...,2.0,334.0,1073.0,391107.00,110981.88,84193.30,91141.62,72,1.1611,2013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12231845,1992973093,O,NE,FacilitySupplierProgram,Y,2,14,292.8,20762.30,12319.74,...,0.0,14.0,292.8,20762.30,12319.74,9815.69,6988.32,76,1.3087,2023
12231851,1992973499,O,FL,FacilitySupplierProgram,Y,7,347,13482.6,641063.20,476894.25,...,0.0,347.0,13482.6,641063.20,476894.25,378674.51,261661.40,76,1.9552,2023
12231863,1992974679,I,PA,RehabTherapy,Y,24,184,1859.2,106824.80,49145.58,...,5.0,184.0,528.0,94916.00,44265.03,31967.37,33009.94,73,1.0119,2023
12232046,1992989792,I,NC,RadiologyImaging,Y,49,521,2670.5,345928.37,59149.45,...,2.0,521.0,787.5,341307.60,58648.60,44668.21,45322.00,73,1.8483,2023
12232047,1992989800,O,WA,FacilitySupplierProgram,Y,3,60,1715.9,76617.50,59415.14,...,0.0,60.0,1715.9,76617.50,59415.14,47300.34,30171.90,77,1.3031,2023

In [62]:
df[mask_not_int].shape[0]/df.shape[0]

0.009787614552221784

In [63]:
df[mask_not_int]['Tot_Srvcs']

80          94896.8
255         59679.9
285           918.3
373           981.6
420          1932.5
             ...
12231845      292.8
12231851    13482.6
12231863     1859.2
12232046     2670.5
12232047     1715.9
Name: Tot_Srvcs, Length: 119724, dtype: float64

In [64]:
df['Tot_Srvcs'] = round(df['Tot_Srvcs'])

In [65]:
mask_not_int = (df['Tot_Srvcs']%1!=0)
df[mask_not_int]

Empty DataFrame
Columns: [Rndrng_NPI, Rndrng_Prvdr_Ent_Cd, Rndrng_Prvdr_State_Abrvtn, Rndrng_Prvdr_Type, Rndrng_Prvdr_Mdcr_Prtcptg_Ind, Tot_HCPCS_Cds, Tot_Benes, Tot_Srvcs, Tot_Sbmtd_Chrg, Tot_Mdcr_Alowd_Amt, Tot_Mdcr_Pymt_Amt, Tot_Mdcr_Stdzd_Amt, Drug_Sprsn_Ind, Drug_Tot_HCPCS_Cds, Drug_Tot_Benes, Drug_Tot_Srvcs, Drug_Sbmtd_Chrg, Drug_Mdcr_Alowd_Amt, Drug_Mdcr_Pymt_Amt, Drug_Mdcr_Stdzd_Amt, Med_Sprsn_Ind, Drug_Tot_HCPCS_Cds.1, Med_Tot_Benes, Med_Tot_Srvcs, Med_Sbmtd_Chrg, Med_Mdcr_Alowd_Amt, Med_Mdcr_Pymt_Amt, Med_Mdcr_Stdzd_Amt, Bene_Avg_Age, Bene_Avg_Risk_Scre, year]
Index: []

[0 rows x 31 columns]

In [66]:
file_name = 'PROV_TYPE'

save_each_year(path,file_name)

# Check all other columns that should be integers

In [69]:
def check_non_integer_columns(percentage):
    cols = df.select_dtypes('number')

    for c in cols:
        mask_temp = (df[c]%1!=0)
        if df[mask_temp].shape[0]/df.shape[0]<percentage:
            df[mask_temp]=round(df[mask_temp])
    return df

In [70]:
check_non_integer_columns(0.01)

,Rndrng_NPI,Rndrng_Prvdr_Ent_Cd,Rndrng_Prvdr_State_Abrvtn,Rndrng_Prvdr_Type,Rndrng_Prvdr_Mdcr_Prtcptg_Ind,Tot_HCPCS_Cds,Tot_Benes,Tot_Srvcs,Tot_Sbmtd_Chrg,Tot_Mdcr_Alowd_Amt,...,Drug_Tot_HCPCS_Cds.1,Med_Tot_Benes,Med_Tot_Srvcs,Med_Sbmtd_Chrg,Med_Mdcr_Alowd_Amt,Med_Mdcr_Pymt_Amt,Med_Mdcr_Stdzd_Amt,Bene_Avg_Age,Bene_Avg_Risk_Scre,year
0,1003000126,I,MD,PrimaryCare,Y,22,665,1648.0,395335.00,146521.84,...,0.0,665.0,1648.0,395335.0,146521.84,116332.66,118271.40,74,2.1114,2013
1,1003000134,I,IL,LabPathology,Y,13,3939,7517.0,1211425.00,282079.49,...,0.0,3939.0,7517.0,1211425.0,282079.49,217960.62,211192.64,76,1.0156,2013
2,1003000142,I,OH,Anesthesia,Y,42,144,661.0,197224.00,63334.30,...,0.0,144.0,661.0,197224.0,63334.30,49752.77,49842.83,63,1.5662,2013
3,1003000407,I,PA,PrimaryCare,Y,37,436,1683.0,240818.00,174786.95,...,0.0,436.0,1683.0,240818.0,174786.95,138741.21,143708.38,76,1.8967,2013
4,1003000423,I,OH,OBGYN,Y,33,63,320.0,31637.00,13176.47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56,1.1882,2013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12232189,1992999569,I,CA,VisionHearing,Y,6,16,24.0,3380.00,3010.25,...,0.0,16.0,24.0,3380.0,3010.25,1588.78,1269.53,72,0.8738,2023
12232190,1992999775,O,OR,FacilitySupplierProgram,Y,24,228,317.0,2682450.00,1076800.05,...,0.0,228.0,317.0,2682450.0,1076800.05,856134.21,798167.83,74,0.9921,2023
12232191,1992999817,I,CA,SurgeryOther,Y,13,18,44.0,21574.18,7201.29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71,0.7118,2023
12232192,1992999825,I,WA,SurgeryOther,Y,34,405,646.0,235765.00,91260.38,...,0.0,405.0,646.0,235765.0,91260.38,69628.19,61665.04,77,1.0682,2023
12232193,1992999874,I,VA,PrimaryCare,Y,8,286,582.0,197647.00,56028.21,...,0.0,286.0,582.0,197647.0,56028.21,44882.54,45412.71,77,2.6601,2023

In [71]:
file_name = 'PROV_TYPE'

save_each_year(path,file_name)

In [ ]:
df16 = pd.read_csv(f'{path}/PROV_2016.csv')
df16

/var/folders/46/mjvmwj6x7n5_cdghvmx10bkm0000gn/T/ipykernel_55177/860743263.py:1: DtypeWarning: Columns (10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  dfPROV = pd.read_csv(f'{path}/MUP_PHY_R25_P05_V20_D23_Prov.csv')

,Rndrng_NPI,Rndrng_Prvdr_Last_Org_Name,Rndrng_Prvdr_First_Name,Rndrng_Prvdr_MI,Rndrng_Prvdr_Crdntls,Rndrng_Prvdr_Ent_Cd,Rndrng_Prvdr_St1,Rndrng_Prvdr_St2,Rndrng_Prvdr_City,Rndrng_Prvdr_State_Abrvtn,...,Bene_CC_PH_Diabetes_V2_Pct,Bene_CC_PH_HF_NonIHD_V2_Pct,Bene_CC_PH_Hyperlipidemia_V2_Pct,Bene_CC_PH_Hypertension_V2_Pct,Bene_CC_PH_IschemicHeart_V2_Pct,Bene_CC_PH_Osteoporosis_V2_Pct,Bene_CC_PH_Parkinson_V2_Pct,Bene_CC_PH_Arthritis_V2_Pct,Bene_CC_PH_Stroke_TIA_V2_Pct,Bene_Avg_Risk_Scre
0,1003000126,Enkeshafi,Ardalan,NaN,M.D.,I,6410 Rockledge Dr Ste 304,NaN,Bethesda,MD,...,45.0,53.0,75.0,75.0,51.0,19.0,4.0,62.0,26.0,2.7545
1,1003000134,Cibull,Thomas,L,M.D.,I,2650 Ridge Ave,Evanston Hospital,Evanston,IL,...,22.0,13.0,75.0,63.0,22.0,19.0,2.0,44.0,6.0,1.1423
2,1003000142,Khalil,Rashid,NaN,M.D.,I,4126 N Holland Sylvania Rd,Suite 220,Toledo,OH,...,44.0,24.0,74.0,75.0,30.0,10.0,NaN,75.0,9.0,1.6448
3,1003000423,Velotta,Jennifer,A,M.D.,I,11100 Euclid Ave,NaN,Cleveland,OH,...,22.0,NaN,75.0,59.0,19.0,22.0,NaN,57.0,NaN,0.7370
4,1003000480,Rothchild,Kevin,B,MD,I,12605 E 16th Ave,NaN,Aurora,CO,...,33.0,16.0,69.0,74.0,27.0,15.0,NaN,63.0,NaN,1.7264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1259338,1992999569,Yuen,Jenny,F,"O.D., F.A.A.O",I,515 Gough St,NaN,San Francisco,CA,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.8738
1259339,1992999775,"Spine Surgery Center Of Eugene, Llc",NaN,NaN,NaN,O,1410 Oak St,Suite 300,Eugene,OR,...,23.0,11.0,68.0,74.0,21.0,15.0,0.0,75.0,NaN,0.9921
1259340,1992999817,Takenishi,Greg,S,M.D.,I,2801 K St Ste 330,NaN,Sacramento,CA,...,NaN,NaN,NaN,72.0,NaN,NaN,0.0,67.0,NaN,0.7118
1259341,1992999825,Deschenes,Geoffrey,R,M.D.,I,1100 9th Ave,Ms:m4-Pfs,Seattle,WA,...,26.0,19.0,63.0,65.0,23.0,17.0,NaN,45.0,7.0,1.0682
1259342,1992999874,Joffe,Gabriella,NaN,NaN,I,5620 Brook Rd,NaN,Richmond,VA,...,50.0,49.0,75.0,75.0,55.0,14.0,6.0,52.0,24.0,2.6601